APPNAME = fillgap

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/N1506393614_2.addedSpecPix.cub \
	to= $(OUTPUT)/specPixlinecubicresults.cub \
	direction=line  > /dev/null;
