APPNAME = hisharpen

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM=$(INPUT)/PSP_008530_1560_BG12_0.cub TO=$(OUTPUT)/bg.cub > /dev/null;
	$(APPNAME) FROM=$(INPUT)/PSP_008530_1560_IR10_0.cub TO=$(OUTPUT)/ir.cub > /dev/null;
