APPNAME = circle2

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/circle2Truth2.cub \
	  samp1=1 \
	  line1=1 \
	  samp2=126 \
	  line2=63 \
	  samp3=1 \
	  line3=126 > /dev/null;
      
