APPNAME = socetlinescankeywords

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/PSP_001488_1750_REDmos_hijitreged_1km_o.cub \
	  to=$(OUTPUT)/PSP_001488_1750_REDmos_keywords.txt >& \
	  $(OUTPUT)/error.txt || true;
