APPNAME = cnetthinner

include $(ISISROOT)/make/isismake.tsts

# History comments 

commands:
	if [ `$(APPNAME) cnet=$(INPUT)/FakeFile.net  to=$(OUTPUT)/fail.net \
	  maxpoints = 20 >& $(OUTPUT)/error.txt` ]; \
	then \
	  true; \
	fi;

