APPNAME = mappt

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/I00824006RDR.lev2.cub \
	  append=false \
	  type=image \
	  sample=41 \
	  line=181 > $(OUTPUT)/mappt1.pvl;
