INCS = Cube.h CubeBsqHandler.h CubeDef.h CubeFormat.h CubeIoHandler.h CubeTileHandler.h

SRCS = CubeBsqHandler.cpp Cube.cpp CubeIoHandler.cpp CubeTileHandler.cpp 

OBJS = $(SRCS:%.cpp=%.o)

include $(ISISROOT)/make/isismake.objs
