APPNAME = phocube

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/n20140805t231914571id30f22.img.cub \
	  to=$(OUTPUT)/sunilluminationmask.cub phase=no emission=no incidence=no \
	  latitude=no longitude=no sunilluminationmask=yes > /dev/null;
