APPNAME = trimfilter

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/trimFilterTruth.cub \
	  samples=5 \
	  lines=5 \
	  minimum=8 > /dev/null;
