# When building ISIS for a public release, be sure that these variables are properly set to reflect
# your current build. Keep in mind that these values are how conda build names its .tar.bz2 build
# file, and so must be unique to other builds sitting in the USGS-Astrogeology channel on Anaconda
# Cloud, or they will be overwritten when you upload this current build. It is always a good idea to
# confirm that you will not be overwriting a file that has already been uploaded by checking the
# channel before building.

# Also keep in mind that there must already be a Release or a Tag by the name <version>_<build_number>
# on the USGS-Astrogeology/ISIS3 repo before invoking the conda build system as this will pull the
# tar.gz of that name to build. After pushing changes for a release build (so as to
# include these changes in the release), but before building using the conda build system, be
# sure to create this Release or Tag.

# This is the version of ISIS that you are building. (Please refer to
# RFC2 (https://github.com/USGS-Astrogeology/ISIS3/wiki/RFC2:-Release-Process) if you are not sure
# about what version you are building.)
# Examples:
#       A Public Release for ISIS3.6.1:                        {% set version = "3.6.1" %}
#       A Release Candidate for ISIS3.6.1:                     {% set version = "3.6.1_RC" %}
#       A custom build of ISIS3.6.1 for the CaSSIS mission:    {% set version = "3.6.1_cassis" %}
{% set version = "8.3" %}

# This is the build number for the current version you are building. If this is the first build of
# this version, the build number will be 0. It is incremented by 1 with every consecutive build of
# the same version.
{% set build_number = "0" %}

package:
  name: isis
  version: {{ version }}.0_RC1

source:
  git_url: 'https://github.com/DOI-USGS/ISIS3.git'
  git_tag: {{ version }}

  # url: 'https://github.com/USGS-Astrogeology/ISIS3/archive/{{ version }}.tar.gz'
  # sha256 is the prefered checksum -- you can get it for a file with:
  # `openssl sha256 <file name>`. Simply run this command with the .tar.gz
  # file specified in the "url" tag above.
  # sha256: '62b88bec88471588feb581e28afc2aa9248bd4e165ad83c448a4c5fa7b59a6e1'

build:
  number: {{ build_number }}

# Shotgun strat on requirements until we can narrow them down
requirements:
  build:
   - ale =0.10.0,<1
   - aom
   - armadillo
   - boost >=1.78.0,<1.79
   - boost-cpp >=1.78.0,<1.79
   - blas
   - usgs-astrogeology::bullet
   - bz2file
   - bzip2
   - cmake >=3.27,<3.28
   - cspice =67
   - csm >=3.0.3,<3.0.4
   - curl >=8.4.0,<8.5
   - cxx-compiler=1.1.2
   - doxygen
   - eigen >=3, <4
   - embree >=3, <4
   - ffmpeg
   - geos >=3.12, <3.13
   - geotiff
   - gmp
   - graphviz
   - conda-forge::gsl >=2.6, <2.7
   - hdf5
   - icu
   - inja
   - jama
   - usgs-astrogeology::kakadu==1
   - kalasiris
   - krb5
   - libgdal >=3.7.0,<3.8
   - libopencv >=4.7,<4.8
   - libpng >=1.6.34,<1.7
   - libprotobuf
   - libtiff >=4.5,<4.6
   - libxml2
   - make
   - mesalib
   - mysql
   - mysql-connector-c
   - nanoflann <1.4
   - nlohmann_json
   - ninja >=1.7.2,<1.8
   - nn
   - opencv >=4.7,<4.8
   - openssl >=3.1.2,<3.2
   - pcl >=1.13,<1.14
   - plio
   - protobuf
   - python >=3.10
   - python_abi >=3.10
   - pytest
   - rclone
   - qhull
   - qt-main=5.15.8
   - qwt <6.3.0
   - sqlite >=3.46.0,<3.47
   - suitesparse <7.7.0
   - superlu
   - swig
   - texlive-core
   - tnt
   - x264
   - xalan-c
   - xerces-c >=3.2.4,<3.3.0a0
   - xorg-kbproto
   - xorg-libice
   - xorg-libsm
   - xorg-libx11
   - xorg-libxi
   - zlib >=1.3,<1.4

  run:
  - {{ pin_compatible('ale', max_pin='x.x.x') }}
  - {{ pin_compatible('armadillo', max_pin='x.x.x') }}
  - {{ pin_compatible('aom', max_pin='x.x') }}
  - {{ pin_compatible('boost', max_pin='x.x') }}
  - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
  - blas
  - {{ pin_compatible('bullet', max_pin='x.x') }}
  - bz2file
  - csm
  - cspice
  - curl
  - eigen
  - {{ pin_compatible('embree', min_pin='x.x', max_pin='x.x') }}
  - {{ pin_compatible('ffmpeg', min_pin='x.x') }}
  - {{ pin_compatible('geos', min_pin='x.x', max_pin='x.x') }}
  - {{ pin_compatible('geotiff', max_pin='x.x') }}
  - geotiff
  - {{ pin_compatible('gsl', min_pin='x.x', max_pin='x.x.x') }}
  - hdf5
  - icu
  - inja
  - jama
  - {{ pin_compatible('jasper', max_pin='x.x') }}
  - {{ pin_compatible('kakadu', max_pin='x') }}
  - kalasiris
  - libcxx
  - libopenblas
  - {{ pin_compatible('libopencv', max_pin='x.x') }}
  - {{ pin_compatible('libpng') }}
  - libtiff
  - mesalib
  - mysql
  - nanoflann
  - nlohmann_json
  - nn
  - {{ pin_compatible('opencv', max_pin='x.x') }}
  - {{ pin_compatible('openssl', min_pin='x', max_pin='x.x') }}
  - {{ pin_compatible('pcl', min_pin='x', max_pin='x.x') }}
  - plio
  - {{ pin_compatible('proj', min_pin='x.x', max_pin='x.x') }}
  - {{ pin_compatible('protobuf', max_pin='x.x') }}
  - qhull
  - {{ pin_compatible('qt-main', max_pin='x.x') }}
  - {{ pin_compatible('qwt', max_pin='x.x') }}
  - rclone
  - {{ pin_compatible('suitesparse', min_pin='x.x', max_pin='x.x') }}
  - superlu
  - tnt
  - x264
  - x265
  - {{ pin_compatible('xerces-c', max_pin='x.x.x') }}
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi

test:
  commands:
    - test -e $PREFIX/lib/libisis${SHLIB_EXT}
    - test -e $PREFIX/include/isis/Isis.h
    - test -e $PREFIX/bin/isisimport
    - ISISROOT=$PREFIX isisimport -HELP


about:
  home: https://github.com/USGS-Astrogeology/ISIS3
  license: CC0-1.0
  license_file: LICENSE.md
  summary: "Integrated Software for Imagers and Spectrometers"
