APPNAME = csspck2spk

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) \
	from=$(INPUT)/kernels.0072.db \
	to=$(OUTPUT)/kernels.0072.txt \
	pairing=$(INPUT)/pck2spk_0050.map > /dev/null;
