channels:
  - conda-forge
  - usgs-astrogeology
  
dependencies:
  - ale =0.11.1
  - aom
  - armadillo
  - boost >=1.76.0,<1.82
  - boost-cpp >=1.76.0,<1.82
  - blas
  - usgs-astrogeology::bullet
  - bz2file
  - bzip2
  - cmake >=3.27,<3.28
  - cspice =67=*_8
  - csm >=3.0.3,<3.0.4
  - curl >=8.4.0,<8.5
  - cxx-compiler=1.7
  - doxygen
  - eigen >=3, <4
  - embree >=3, <4
  - ffmpeg
  - geos >=3.12,<3.13
  - geotiff
  - gdal >=3.7,<3.9
  - gmp
  - graphviz
  - conda-forge::gsl >=2.6, <2.7
  - hdf5
  - highfive
  - icu
  - inja
  - jama
  - usgs-astrogeology::kakadu==1
  - kalasiris
  - krb5
  - libgdal >=3.7,<3.9
  - libopencv >=4.5,<4.10
  - libpng >=1.6.34,<1.7
  - libprotobuf >=4,<5
  - libtiff >=4.5,<4.8
  - libxml2
  - make
  - mesalib
  - mkl
  - mysql
  - mysql-connector-c
  - nanoflann <1.4
  - nlohmann_json=3.11.2
  - ninja >=1.10,<1.11
  - nn
  - opencv >=4.5,<4.10
  - openssl >=3.1.2,<3.5
  - pcl >=1.13,<1.14
  - pdal=2.6
  - plio=1.5.3
  - protobuf >=4,<5
  - python >=3.9
  - python_abi >=3.9
  - pytest
  - rclone
  - qhull
  - qt-main >=5.15,<5.16
  - qwt <6.3.0
  - spiceypy >=6.0.0,<7.0.0
  - sqlite >=3.46.0,<3.47
  - suitesparse <7.7.0
  - superlu
  - swig
  - texlive-core
  - tnt
  - usgscsm
  - x264
  - xalan-c
  - xerces-c >=3.2.4,<3.3.0a0
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib >=1.3,<1.4.0a0
