channels:
  - jessemapel
  - conda-forge
  - probcomp
  - defaults

dependencies:
  - ale>=0.8.7
  - armadillo
  - boost=1.72.0
  - blas
  - usgs-astrogeology::bullet
  - bz2file
  - bzip2
  - cmake >=3.15
  - cspice
  - csm=3.0.3
  - curl
  - doxygen
  - eigen < 3.4
  - embree
  - ffmpeg>=3.4.1
  - geos=3.7.1
  - geotiff
  - gmp
  - graphviz
  - gsl
  - hdf5
  - icu
  - inja
  - jama
  - jpeg
  - usgs-astrogeology::kakadu==1
  - krb5
  - libpng>=1.6.34
  - libprotobuf
  - libtiff>=4.0
  - libxml2
  - make
  - mesalib
  - mysql
  - mysql-connector-c
  - nanoflann
  - nlohmann_json
  - ninja==1.7.2
  - nn
  - opencv>=4.5.2
  - openssl>=1.1.1k
  - pcl>=1.10.1
  - protobuf
  - python>=3.7.11
  - qhull
  - qt>=5.9.6
  - qwt
  - sqlite
  - suitesparse
  - superlu
  - tnt
  - x264
  - xalan-c
  - conda-forge::xerces-c=3
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib
