channels:
  - conda-forge
  - usgs-astrogeology
  
dependencies:
  - ale >=1.0.2,<2
  - aom
  - armadillo
  - blas
  - bullet >=3.25
  - bz2file
  - bzip2
  - cmake >=3.27,<3.28
  - cspice =67
  - csm >=3.0.3,<3.0.4
  - curl >=8.14.1,<9
  - cxx-compiler=1.9
  - doxygen
  - eigen >=3, <4
  - embree >=3, <4
  - ffmpeg
  - geos >=3.14,<3.15
  - geotiff
  - gdal >=3.12,<4
  - gmp
  - gcovr
  - graphviz
  - conda-forge::gsl >=2.6, <2.7
  - hdf5
  - highfive
  - icu
  - inja
  - jama
  - kalasiris
  - krb5
  - libboost >=1.88.0,<1.89
  - libgdal >=3.12,<4
  - libopencv >=4.12,<5
  - libpng >=1.6.34,<1.7
  - libprotobuf >=6,<7
  - libtiff >=4.5,<4.8
  - libvulkan-headers
  - libxml2
  - make
  - mesalib
  - mysql
  - nanoflann>=1.4.2,<1.5
  - nlohmann_json=3.11.2
  - ninja >=1.10,<1.11
  - nn
  - opencv >=4.12,<5
  - openssl >=3.5,<4
  - pcl >=1.15,<1.16
  - pdal >=2.8.4,<3
  - plio=1.5.3
  - protobuf >=6,<7
  - python >=3.9
  - python_abi >=3.9
  - pytest
  - rclone
  - qhull
  - qt6-main >=6,<7
  - qwt =6.3.0
  - spiceypy >=6,<7
  - spiceql >=1.2.4,<2
  - sqlite >=3.46.0,<4
  - suitesparse <7.7.0
  - superlu
  - swig
  - tnt
  - usgscsm
  - x264
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib
