APPNAME = pad

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to= $(OUTPUT)/padTruth2.cub \
	  left=0 \
	  right=0 \
	  top=10 \
	  bottom=0 > /dev/null;
