^DATA_SET_MAP_PROJECTION     = String
MAP_PROJECTION_TYPE          = String
PROJECTION_LATITUDE_TYPE     = Enum
A_AXIS_RADIUS                = (Real, 6)
B_AXIS_RADIUS                = (Real, 6)
C_AXIS_RADIUS                = (Real, 6)
FIRST_STANDARD_PARALLEL      = Real
SECOND_STANDARD_PARALLEL     = Real
COORDINATE_SYSTEM_NAME       = String
POSITIVE_LONGITUDE_DIRECTION = String
KEYWORD_LATITUDE_TYPE        = String
CENTER_LATITUDE              = Real
CENTER_LONGITUDE             = Real
REFERENCE_LATITUDE           = Enum
REFERENCE_LONGITUDE          = Enum
LINE_FIRST_PIXEL             = Integer
LINE_LAST_PIXEL              = Integer
SAMPLE_FIRST_PIXEL           = Integer
SAMPLE_LAST_PIXEL            = Integer
MAP_PROJECTION_ROTATION      = Real
MAP_RESOLUTION               = Real
MAXIMUM_LATITUDE             = (Real, 6)
MINIMUM_LATITUDE             = (Real, 6)
LINE_PROJECTION_OFFSET       = (Real, 4)
SAMPLE_PROJECTION_OFFSET     = (Real, 4)
EASTERNMOST_LONGITUDE        = (Real, 6)
WESTERNMOST_LONGITUDE        = (Real, 6)
MAP_SCALE                    = Real
IMAGE_HEIGHT                 = Real

