APPNAME = hifurrows

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/TRA_000880_1905_RED0_0.cub \
	to= $(OUTPUT)/hifurrowsTruth.cub new_version=true lowpass=true > /dev/null;
