APPNAME = mrf2isis

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/FSL_CDR_LV2_00200_1Q.LBL \
	to=$(OUTPUT)/FSL_CDR_LV2_00200_1Q.cub > /dev/null;
	$(APPNAME) from=$(INPUT)/LSL_CDR_LV2_00300_1Q.LBL \
	to=$(OUTPUT)/LSL_CDR_LV2_00300_1Q.cub > /dev/null;
