APPNAME = hinoise2

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/PSP_001853_1900_RED9_0.cub \
          to=$(OUTPUT)/PSP_001853_1900_RED9_0-binningIsOne.cub \
          remove=true > /dev/null;

	$(APPNAME) from=$(INPUT)/PSP_001853_1900_RED9_1.cub \
          to=$(OUTPUT)/PSP_001853_1900_RED9_1-binningIsOne.cub \
          remove=true > /dev/null;

