APPNAME = circle

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/circleTruth2.cub \
	  sample=0 \
	  line=80 \
	  radius=60.5 > /dev/null;
