APPNAME = fillgap

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/CM_1540484434_1_001.ir.addedSpecPix.cub \
	to= $(OUTPUT)/bandcubicresults.cub \
	direction=band > /dev/null;
