APPNAME = algebra

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from1=$(INPUT)/isisTruth.cub+1 \
	  to= $(OUTPUT)/algebraTruth1.cub \
	  operator=unary \
	  a=1 \
	  c=0 > /dev/null;
