PDS_VERSION_ID = Enum
RECORD_TYPE = Enum
RECORD_BYTES = Integer
FILE_RECORDS = Integer
LABEL_RECORDS = Integer
INTERCHANGE_FORMAT = Enum
DATA_SET_ID = String
OBSERVATION_ID = String
PRODUCT_VERSION_ID = String
INSTRUMENT_NAME = String
TARGET_NAME = String
MISSION_PHASE_NAME = String
ORBIT_NUMBER = Integer
RATIONALE_DESC = String
SOFTWARE_NAME = String
MD5_CHECKSUM = String

LRO:SPACECRAFT_CLOCK_PREROLL_COUNT = String
SPACECRAFT_CLOCK_START_COUNT = String
SPACECRAFT_CLOCK_STOP_COUNT = String
UPLOAD_ID = String
DATA_QUALITY_ID = String

INSTRUMENT_MODE_ID = String
FILTER_NUMBER = String