APPNAME = socetlinescankeywords

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/P01_001602_1701_XI_09S091W.8bit.cub \
	  to=$(OUTPUT)/P01_001602_1701_XI_09S091W_keywords.txt > /dev/null;
