APPNAME = cropspecial

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/allspecial.cub+1 to=$(OUTPUT)/keptnulls.cub \
	NULL=no HRS=yes LRS=yes HIS=yes LIS=yes \
	> /dev/null;
