APPNAME = stretch

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth2.cub \
	  to=$(OUTPUT)/stretchTruth2.cub \
	  null="hrs" \
	  lis="NULL" \
	  lrs="Lis" \
	  his="lRs" \
	  hrs="HiS" > /dev/null;
