ProjectionName = EQUIRECTANGULAR
CenterLongitude = {{ IMAGE_MAP_PROJECTION.CENTER_LONGITUDE.Value }}
TargetName         = {{ TARGET_NAME.Value }}
EquatorialRadius   = 3396190.0 <meters>
PolarRadius        = 3376200.0 <meters>
LatitudeType       = {{ IMAGE_MAP_PROJECTION.PROJECTION_LATITUDE_TYPE.Value }}
LongitudeDirection = {{ IMAGE_MAP_PROJECTION.POSITIVE_LONGITUDE_DIRECTION.Value }}
LongitudeDomain    = 360
MinimumLatitude    = {{ IMAGE_MAP_PROJECTION.MINIMUM_LATITUDE.Value }}
MaximumLatitude    = {{ IMAGE_MAP_PROJECTION.MAXIMUM_LATITUDE.Value }}
MinimumLongitude   = {{ IMAGE_MAP_PROJECTION.EASTERNMOST_LONGITUDE.Value }}
MaximumLongitude   = {{ IMAGE_MAP_PROJECTION.WESTERNMOST_LONGITUDE.Value }}
UpperLeftCornerX   = -110.0
UpperLeftCornerY   = -2366138.0
PixelResolution    = {{ IMAGE_MAP_PROJECTION.MAP_SCALE.Value }}
Scale              = {{ IMAGE_MAP_PROJECTION.MAP_RESOLUTION.Value }} <pixels/degree>
TrueScaleLatitude  = -40.0
CenterLatitude     = {{ IMAGE_MAP_PROJECTION.CENTER_LATITUDE.Value }}
