ProjectionName = EQUIRECTANGULAR
CenterLongitude = {{ IMAGE_MAP_PROJECTION.CENTER_LONGITUDE.Value }}
TargetName         = {{ TARGET_NAME.Value }}
EquatorialRadius   = {{ IMAGE_MAP_PROJECTION.A_AXIS_RADIUS.Value }} <meters>
PolarRadius        = {{ IMAGE_MAP_PROJECTION.B_AXIS_RADIUS.Value }} <meters>
LatitudeType       = {{ IMAGE_MAP_PROJECTION.PROJECTION_LATITUDE_TYPE.Value }}
LongitudeDirection = {{ IMAGE_MAP_PROJECTION.POSITIVE_LONGITUDE_DIRECTION.Value }}
LongitudeDomain    = 360
MinimumLatitude    = {{ IMAGE_MAP_PROJECTION.MINIMUM_LATITUDE.Value }}
MaximumLatitude    = {{ IMAGE_MAP_PROJECTION.MAXIMUM_LATITUDE.Value }}
MinimumLongitude   = {{ IMAGE_MAP_PROJECTION.EASTERNMOST_LONGITUDE.Value }}
MaximumLongitude   = {{ IMAGE_MAP_PROJECTION.WESTERNMOST_LONGITUDE.Value }}
UpperLeftCornerX   = -110.0
UpperLeftCornerY   = -2366138.0
PixelResolution    = {{ IMAGE_MAP_PROJECTION.MAP_SCALE.Value }} <meters/pixel>
Scale              = {{ IMAGE_MAP_PROJECTION.MAP_RESOLUTION.Value }} <pixels/degree>
TrueScaleLatitude  = {{ IMAGE_MAP_PROJECTION.CENTER_LONGITUDE.Value }}
CenterLatitude     = {{ IMAGE_MAP_PROJECTION.CENTER_LATITUDE.Value }}
