APPNAME = algebra

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from1=$(INPUT)/isisTruth.cub+1 \
	  from2=$(INPUT)/isisTruth.cub+2 \
	  to=$(OUTPUT)/algebraTruth3.cub \
	  a=1 \
	  b=1 \
	  c=0 > /dev/null;
