APPNAME = vimscal

V1483214528_1.ir.nodark.cal.cub.TOLERANCE = 0.00000000004

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM=$(INPUT)/V1483214528_1.ir.cub \
	  TO=$(OUTPUT)/V1483214528_1.ir.nodark.cal.cub \
	  dark=false > /dev/null;
