APPNAME = clemuvviscal

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM=$(INPUT)/lua1841h.cub \
	TO=$(OUTPUT)/lua1841h.truth.cub TCOR=true\
	> /dev/null;
	$(APPNAME) FROM=$(INPUT)/lub0008e.cub \
	TO=$(OUTPUT)/lub0008e.truth.cub TCOR=true\
	> /dev/null;
	$(APPNAME) FROM=$(INPUT)/luc0890d.cub \
	TO=$(OUTPUT)/luc0890d.truth.cub TCOR=true\
	> /dev/null;
	$(APPNAME) FROM=$(INPUT)/lud0917d.cub \
	TO=$(OUTPUT)/lud0917d.truth.cub TCOR=true\
	> /dev/null;
	$(APPNAME) FROM=$(INPUT)/lue1007d.cub \
	TO=$(OUTPUT)/lue1007d.truth.cub TCOR=true\
	> /dev/null;

