APPNAME = outline

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/outlineTruth1.cub \
	  boundary=1001.0 \
	  clear=no \
	  edges=no > /dev/null;
