APPNAME = findgaps

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/findGapsTest_endOfBandGap.cub                        \
	to=$(OUTPUT)/endOfGapCubeResults.cub log=$(OUTPUT)/endOfBandGapLogResults.pvl \
	> /dev/null;                                                                  \
