APPNAME = vikclean

vikcleanTruth.cub.TOLERANCE = 1.0

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/f348b26.cub to=$(OUTPUT)/vikcleanTruth.cub \
	  remove=yes > /dev/null;
