APPNAME = ctxevenodd

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM= $(INPUT)/P01_001473_2479_XI_67N185W.cal.cub \
	TO= $(OUTPUT)/P01_001473_2479_XI_67N185W.evenodd.cub > /dev/null;
