APPNAME = kaguyasp2isis

labels.txt.IGNORELINES = Bytes StartByte ByteOrder TileSamples TileLines

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/SP_2B2_01_00896_N233_E3127.spc \
	  to=$(OUTPUT)/SP_2B2_01_00896_N233_E3127.txt > /dev/null;
