APPNAME = edrget

include $(ISISROOT)/make/isismake.tsts

commands:

	$(ECHO) "TESTS DISABLED, SEE ISSUE #4666" > $(OUTPUT)/message.txt

# 	$(APPNAME) URL=ftp://pdsimage2.wr.usgs.gov/cdroms/Viking_Orbiter/vo_1004/f253sxx/f253s05.imq TOPATH=$(OUTPUT) > /dev/null;
# 
