APPNAME = higlob

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/PSP_001331_2260_IR10_0.cub \
	  to=$(OUTPUT)/higlob_default_truth0.cub \
	  flip=none > /dev/null;
	$(APPNAME) from=$(INPUT)/PSP_001331_2260_IR10_1.cub \
	  to=$(OUTPUT)/higlob_default_truth1.cub \
	  flip=none > /dev/null;
