APPNAME = thmdriftcor

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/I02446002RDR_b9.cub \
	atm=$(INPUT)/I02446002RDR_b10.cub \
	to=$(OUTPUT)/test_thmdriftcor.cub > /dev/null;
