APPNAME = rosvirtis2isis
APPNAME2 = catlab

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/i1_00237319854.qub to=$(OUTPUT)/i1_00237319854.cub > /dev/null; 
	$(APPNAME2) from=$(OUTPUT)/i1_00237319854.cub to=$(OUTPUT)/i1_00237319854.pvl > /dev/null; 

