APPNAME = pixel2map

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/C1596102183_1.ir.cub \
               to=$(OUTPUT)/C1596102183_1.ir.polar.cub \
			   map=$(ISISROOT)/appdata/templates/maps/polarstereographic.map \
			   > /dev/null;
