APPNAME = pad

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to= $(OUTPUT)/padTruth1.cub \
	  left=0 \
	  right=100 \
	  top=100 \
	  bottom=0 > /dev/null;
