APPNAME = tgocassisunstitch

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/CAS-MCO-2016-11-22T16:10:43.505.cub \
	           outputprefix=$(OUTPUT)/CAS-MCO-2016-11-22T16:10:43.505.cub > /dev/null;
	mv $(OUTPUT)/CAS-MCO-2016-11-22T16:10:43.505.lis \
	   $(OUTPUT)/CAS-MCO-2016-11-22T16:10:43.505.txt;
