# history 2015-03-08 Jeannie Backer - Original Version.
#                        Code Coverage 93.75% scope, 100% line and function.
#                        Coverage Complete until we can figure out a case where plate ID is invalid.
BLANKS = "%-6s"    
LENGTH = "%-40s"

include $(ISISROOT)/make/isismake.tststree
