APPNAME = mappt

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/I00824006RDR.lev2.cub \
	  to=$(OUTPUT)/mappt3.pvl \
	  append=false \
	  type=projection \
	  x=-51500 \
	  y=-105500 > /dev/null;
