APPNAME = isis2ascii

include $(ISISROOT)/make/isismake.tsts
vesta64ascii.txt.SKIPLINES = 1


commands:
	$(APPNAME) from = $(INPUT)/vesta64_dtm_top.cub \
	  to = $(OUTPUT)/vesta64ascii.txt > /dev/null;
