APPNAME = hinoise

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/PSP_001853_1900_BG12_0.cub \
          to=$(OUTPUT)/PSP_001853_1900_BG12_0-binningNotOne.cub \
          > /dev/null;
