APPNAME = stretch

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/stretchTruth2.cub \
	  to=$(OUTPUT)/stretchTruth3.cub \
	  null="HRS" \
	  lis="N" \
	  lrs="LIS" \
	  his="LRS" \
	  hrs="HIS" > /dev/null;
