APPNAME = histitch

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from1=$(INPUT)/PSP_001446_1790_RED2_0.cub \
	  to=$(OUTPUT)/histitch_RED0.cub > /dev/null;
	$(APPNAME) from1=$(INPUT)/PSP_001446_1790_RED2_1.cub \
	  to=$(OUTPUT)/histitch_RED1.cub > /dev/null;
