APPNAME = circle2

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/circle2Truth1.cub \
	  samp1=12 \
	  line1=1 \
	  samp2=15 \
	  line2=1 \
	  samp3=1 \
	  line3=10 > /dev/null;
