APPNAME = mappt

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/I00824006RDR.lev2.cub \
	  to=$(OUTPUT)/mappt2.pvl \
	  append=false \
	  type=ground \
	  latitude=-1.7798488125312 \
	  longitude=352.13074447388 > /dev/null;
