APPNAME = isisminer

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) config=$(INPUT)/gisUnion_test0.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
	$(APPNAME) config=$(INPUT)/gisUnion_test1.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
	$(APPNAME) config=$(INPUT)/gisUnion_test2.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
	$(APPNAME) config=$(INPUT)/gisUnion_test3.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
	$(APPNAME) config=$(INPUT)/gisUnion_test4.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
	$(APPNAME) config=$(INPUT)/gisUnion_test5.conf \
	  parameters="inputdir:$(INPUT)@outputdir:$(OUTPUT)" > /dev/null;
