APPNAME = hinoise2

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/ATL_20050526T055627_BG12_1.cub \
          to=$(OUTPUT)/ATL_20050526T055627_BG12_1-binningNotOne.cub \
          remove=true > /dev/null;
