APPNAME = outline

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/outlineTruth2.cub \
	  boundary=1001.0 \
	  clear=yes \
	  edges=yes > /dev/null;
