APPNAME = grid

# Added to test that grid works on mosaics, which notably will not have camera models.

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/lroMosaicOntop.cub \
	to=$(OUTPUT)/lroMosaicOntop.cub > /dev/null;

