APPNAME = circle

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/Sample.cub \
	  to= $(OUTPUT)/testCircle_userInput.cub+32bit \
	  sample=500 line=500 radius=300 definition=centerrad \
	  > /dev/null;


	  