APPNAME = camtest

include $(ISISROOT)/make/isismake.tsts

commands:
	echo "This program has a dummy test to prevent " \
	     "errors on camera model changes, and because" \
	     "this program is only for internal testing." > $(OUTPUT)/truth.txt;
