APPNAME = poly

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from= $(INPUT)/isisTruth.cub \
	  to= $(OUTPUT)/polyTruth2.cub \
	  mult1=.5 \
	  mult2=.6 \
	  mult3=.7 \
	  mult4=.8 \
	  mult5=.9 \
	  mult6=1.0 \
	  mult7=1.1 \
	  mult8=1.2 > /dev/null;
