APPNAME = pad

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to= $(OUTPUT)/padTruth3.cub \
	  left=50 \
	  right=50 \
	  top=50 \
	  bottom=50 > /dev/null;
