APPNAME = isisui

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) circle from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/circle.cub sample=10 line=15 rad=27  > $(OUTPUT)/standardOutTruth3.pvl;
