PDS_VERSION_ID                           = Enum
RECORD_TYPE                              = Enum
RECORD_BYTES                             = Integer
FILE_RECORDS                             = Integer
LABEL_RECORDS                            = Integer
^IMAGE                                   = String
^INSTRUMENT_POINTING_TABLE               = String 
^INSTRUMENT_POSITION_TABLE               = String 
^BODY_ROTATION_TABLE                     = String 
^SUN_POSITION_TABLE                      = String 
NOT_APPLICABLE_CONSTANT                  = Integer
DATA_SET_ID                              = String
DATA_SET_NAME                            = String
PRODUCER_INSTITUTION_NAME                = String
PRODUCER_ID                              = String
PRODUCER_FULL_NAME                       = String
OBSERVATION_ID                           = String
PRODUCT_ID                               = String
PRODUCT_VERSION_ID                       = String
SPACECRAFT_NAME                          = String
INSTRUMENT_ID                            = String
INSTRUMENT_NAME                          = String
INSTRUMENT_HOST_ID                       = String
INSTRUMENT_HOST_NAME                     = String
TARGET_NAME                              = String
MISSION_PHASE_NAME                       = String
ORBIT_NUMBER                             = Integer
SOURCE_PRODUCT_ID                        = String
RATIONALE_DESC                           = String
SOFTWARE_NAME                            = String
SAMPLE_DETECTORS                         = Integer 
LINE_DETECTORS                           = Integer 
INSTRUMENT_TYPE                          = Enum
EPHEMERIS_TIME                           = Real
FOCAL_PLANE_X_DEPENDENCY                 = Integer
EXPOSURE_DURATION                        = (Real, 4)
IMAGE_JITTER_CORRECTED                   = Integer
SHAPE_MODEL                              = String
A_AXIS_RADIUS                            = (Real, 2)
B_AXIS_RADIUS                            = (Real, 2)
C_AXIS_RADIUS                            = (Real, 2)
BODY_FRAME_CODE                          = Integer
IDEAL_FOCAL_LENGTH                       = (Real, 12)
IDEAL_PIXEL_PITCH                        = (Real, 12)
IDEAL_TRANSX                             = (Real, 12)
IDEAL_TRANSY                             = (Real, 12)
IDEAL_TRANSS                             = (Real, 12)
IDEAL_TRANSL                             = (Real, 12)
MISSION_NAME           = String
INSTRUMENT_MODE_ID     = String



# Time Parameters Group
MRO:OBSERVATION_START_TIME               = Enum
MRO:OBSERVATION_START_COUNT              = Enum
START_TIME                               = Enum
SPACECRAFT_CLOCK_START_COUNT             = String
STOP_TIME                                = Enum
SPACECRAFT_CLOCK_STOP_COUNT              = String
PRODUCT_CREATION_TIME                    = Enum

# Image Object
DESCRIPTION                              = String
LINES                                    = Integer
LINE_SAMPLES                             = Integer
BANDS                                    = Integer
OFFSET                                   = Real
SCALING_FACTOR                           = Real
SAMPLE_BITS                              = Integer
SAMPLE_BIT_MASK                          = ("Binary",16)
SAMPLE_TYPE                              = Enum
FILTER_NAME                              = String
CENTER_FILTER_WAVELENGTH                 = Real
BAND_WIDTH                               = Real
BAND_STORAGE_TYPE                        = Enum
CORE_NULL                                = Integer
CORE_LOW_REPR_SATURATION                 = Integer
CORE_LOW_INSTR_SATURATION                = Integer
CORE_HIGH_REPR_SATURATION                = Integer
CORE_HIGH_INSTR_SATURATION               = Integer
VALID_MINIMUM                            = Integer
INTERCHANGE_FORMAT                       = Enum
ROWS                                     = Integer 
COLUMNS                                  = Integer
ROW_BYTES                                = Integer
ROW_SUFFIX_BYTES                         = Integer
SOURCE_LINE_SAMPLES                      = Integer
SOURCE_LINES                             = Integer
FIRST_LINE_SAMPLE                        = Real
FIRST_LINE                               = Real

# Table Objects
TIME_DEPENDENT_FRAMES                    = Real
CONSTANT_FRAMES                          = Real
CONSTANT_ROTATION                        = Real
CK_TABLE_START_TIME                      = Real
CK_TABLE_END_TIME                        = Real
CK_TABLE_ORIGINAL_SIZE                   = Integer
COLUMN_NUMBER                            = Integer
NAME                                     = String
START_BYTE                               = Integer
DATA_TYPE                                = Enum
BYTES                                    = Integer
CACHE_TYPE                               = Enum
SPK_TABLE_START_TIME                     = Real
SPK_TABLE_END_TIME                       = Real
SPK_TABLE_ORIGINAL_SIZE                  = Integer
SOLAR_LONGITUDE                          = Real
