APPNAME = poly

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from= $(INPUT)/isisTruth.cub \
	  to= $(OUTPUT)/polyTruth3.cub \
	  mult1=1 \
	  mult2=2 \
	  mult3=3 \
	  add=7 > /dev/null;
