INCS = MocWideAngleCamera.h MocWideAngleDistortionMap.h MocWideAngleDetectorMap.h
SRCS = MocWideAngleCamera.cpp MocWideAngleDistortionMap.cpp MocWideAngleDetectorMap.cpp
OBJS = $(SRCS:%.cpp=%.o)

include $(ISISROOT)/make/isismake.objs
