"Turner, Scott" <Scott.Turner@jhuapl.edu> 
12/03/2007 03:12 PM	To
Kris J Becker <kbecker@usgs.gov>, "Prockter, Louise M." <Louise.Prockter@jhuapl.edu>, Mark Robinson 
<mrobinson@asu.edu>
cc

bcc

Subject
MDIS Geometric Distortion Model Part II
	
		
		
		Kris,

I just realized, for absolute clarity, I am using the following values for
the other pieces of the model which I did not fit:

   Detector Center in Pixels (512,512)
   Diagonal Scale Factors (assume 14 micrometer pixels): 71.42857
   Off Diagonal Elements: 0.0

Sorry for neglecting to mention these in my previous email.

Scott
