APPNAME = socetnet2isis

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/absolute.atf \
	to=$(OUTPUT)/cabeus.net \
	measurements=adjusted \
	point_id_prefix=SS_ > /dev/null;