INCS = Message.h
SRCS = ArraySubscriptNotInRange.cpp FileCreate.cpp FileOpen.cpp FileRead.cpp FileWrite.cpp KeywordAmbiguous.cpp KeywordBlockEndMissing.cpp KeywordBlockInvalid.cpp KeywordBlockStartMissing.cpp KeywordDuplicated.cpp KeywordNotArray.cpp KeywordNotFound.cpp KeywordUnrecognized.cpp KeywordValueBad.cpp KeywordValueExpected.cpp KeywordValueNotInList.cpp KeywordValueNotInRange.cpp MemoryAllocationFailed.cpp MissingDelimiter.cpp

OBJS = $(SRCS:%.cpp=%.o)

include $(ISISROOT)/make/isismake.objs
