APPNAME = circle

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/Sample.cub \
	  to= $(OUTPUT)/testCircle2_userInput.cub+32bit \
	  samp1=612 line1=202 samp2=412 line2=502 \
	  samp3=612 line3=802 definition=points \
	  > /dev/null;