APPNAME = std2isis

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM=$(INPUT)/PSP_001892_1715_COLOR.JP2 \
	TO=$(OUTPUT)/PSP_001892_1715_COLOR.cub \
        > /dev/null;

	$(APPNAME) FROM=$(INPUT)/PSP_001892_1715_RED.JP2 \
	TO=$(OUTPUT)/PSP_001892_1715_RED.cub \
        > /dev/null;
