name: Cherrypick bugfixes to release branch
on:
  push:
    branches:
      - dev
jobs:
  check_labels:
    runs-on: ubuntu-latest
    name: Check PR labels action step
    outputs: 
      result: ${{steps.check_pr_labels.outputs.result}}
    steps:
    - id: check_pr_labels
      uses: 3pointer/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["bug"]'
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"
  release_pull_request:
    needs: check_labels
    if: contains(needs.check_labels.outputs.result, 'true')
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: get_latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - id: get_short_version
      run: |
        major_minor=$(echo ${{steps.get_latest_tag.outputs.tag}} | cut -d '.' -f 1,2)
        echo "::set-output name=major_minor::$major_minor"
    - name: Create PR to branch
      uses: adamtharani/github-action-cherry-pick@master
      with:
        pr_branch: ${{steps.get_short_version.outputs.major_minor}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false

