name: Conda Build Recipe

on: [push]

jobs: 
  test_conda_build_recipe:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: setup conda env
        uses: actions/setup-python@v2
        with: 
          python-version: 3.6
      - name: Install dependencies
        run: |
          - test -e $PREFIX/lib/libisis${SHLIB_EXT}
          - test -e $PREFIX/include/isis/Isis.h
