name: Conda Build Recipe

on: [push]

jobs: 
  test_conda_build_recipe:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
  test:
    commands:
      - test -e $PREFIX/lib/libisis${SHLIB_EXT}
      - test -e $PREFIX/include/isis/Isis.h


