package:
  name: isis
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ISIS3.git'
  git_tag: {{ version }}

build:
  number: {{ build_number }}

requirements:
  build:
    - boost=1.68.0
    - cmake >=3.15
    - doxygen
    - inja
    - make
    - ninja==1.7.2
    - openssl>=1.0.0,<1.1.0
    - protobuf=3.9.1
    - xalan-c

test:
  on: [push]
  commands:
    - test -e $PREFIX/lib/libisis${SHLIB_EXT}
    - test -e $PREFIX/include/isis/Isis.h