package:
name: hello
version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/USGS-Astrogeology/CSM-CameraModel.git
build:
  string: {{ environ.get("GIT_DESCRIBE_HASH", "") }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - vc 14  # [win]
    - cmake >=3.10
    - libcsm
    - vc 14  # [win]
  run:
    - vc  # [win]