name: Conda Build Recipe

on: [push]

jobs: 
  test_conda_build_recipe:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: setup conda env
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: create conda env
        run: |
          conda create -n isis python=3.6
          conda activate isis

      - name: add conda channels
        run: |
          conda config --env --add channels conda-forge
          conda config --env --add channels usgs-astrogeology

      - name: download mamba 
        run: |
          conda install -n base -c conda-forge mamba

      - name: download ISIS and its dependencies
        run: |
          mamba install -c usgs-astrogeology isis
        
      - name: set up env vars
        run: |
            python $CONDA_PREFIX/scripts/isisVarInit.py

      - name: deactivate then reactivate env
        run: |
          conda deactivate
          conda activate isis

      - name: install conda deps
        run: |
            $CONDA/bin/conda env update --file environment.yml --name base
