name: Conda Build Recipe

on: [push]

jobs: 
  test_conda_build_recipe:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
      - uses: actions/checkout@v2

      - name: check header file in include dir
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Isis.h"