name: GH Cherrypick bugfixes/features for LTS/Prod

env:
  GITHUB_SHA: ${{ github.sha }}

on:
  push:
    branches:
      - dev
      
jobs:
  # Check if the PR is a bugfix/feature
  check_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Detect Max LTS/Prod Version, Bugfix/Feature Checkboxes
    # Make the output of this job available to other jobs
    outputs: 
      maxlts: ${{ steps.parse_lts.outputs.maxlts }}
      maxprod: ${{ steps.parse_prod.outputs.maxprod }}
      result: ${{steps.execute_py_script.outputs.result}}
    steps:
    - name: Checkout files (only the PR Label Checker)
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/pr_label_checker.py
          .github/requirements.txt
        sparse-checkout-cone-mode: false
    - name: Fetch/Parse LTS Version
      id: parse_lts
      run: |
        MAX_LTS="$( \
        git ls-remote --heads origin | \
        sed '/-lts/!d; s/^.*refs\/heads\///; s/-lts//; /^[0-9][0-9]*$/!d' | \
        sort -n | \
        tail -n 1 \
        )"
        echo "maxlts=${MAX_LTS}-lts" >> $GITHUB_OUTPUT
    - name: Fetch/Parse Prod Version
      id: parse_prod
      run: |
        MAX_PROD="$( \
        git ls-remote --heads origin | \
        sed '/-prod/!d; s/^.*refs\/heads\///; s/-prod//; /^[0-9][0-9]*$/!d' | \
        sort -n | \
        tail -n 1 \
        )"
        echo "maxprod=${MAX_PROD}-prod" >> $GITHUB_OUTPUT
    - name: List files in current Directory
      run: ls .github
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/requirements.txt
    - name: Write Output
      id: execute_py_script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_API_URL: ${{ secrets.GITHUB_API_URL }}
        GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
      run: echo "result=$(python ./.github/pr_label_checker.py)" >> "$GITHUB_OUTPUT"
    - name: Show Output
      run: |
        echo "checkboxes... ${{ steps.execute_py_script.outputs.result }}"
        echo "max lts... ${{ steps.execute_py_script.outputs.maxlts }}"
        echo "max prod... ${{ steps.execute_py_script.outputs.maxprod }}"


  cherrypick-lts:
    needs: check_labels
    # Only run this step if code was a bugfix
    if: contains(needs.check_labels.outputs.result, 'bugfix_')
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0} # bash login mode so conda can auto activate isis env
    permissions:
      pull-requests: write
      contents: write
    env:
      MAX_LTS: ${{ needs.check_labels.outputs.maxlts }}
    steps:
      - name: Get PR number
        id: getpr
        uses: bcgov/action-get-pr@v0.1.0
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: '${{ env.MAX_LTS }}' # This branch must exist in the repo.  Target LTS changes branch.
          fetch-depth: '0'
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Cherry Pick
        id: cherryPickStep
        continue-on-error: true
        run: git cherry-pick -m 1 $GITHUB_SHA
      - name: Failed Cherry Pick - Comment
        if: steps.cherryPickStep.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          pr-number: '${{ steps.getpr.outputs.pr }}'
          message: |
            Maintainers (@jrcain-usgs @Kelvinrr): Please cherry-pick this bugfix to LTS.  
            PR:  #${{ steps.getpr.outputs.pr }}
            SHA: ${{ github.sha }}.  

            You may use the following commands to cherry-pick 
            (Assuming you have the DOI-USGS/ISIS3 repo as a remote named `upstream`):
            ```
            git fetch upstream
            git checkout -b cherry-${{ steps.getpr.outputs.pr }} upstream/${{ env.MAX_LTS }}
            git cherry-pick -m 1 ${{ github.sha }}

            # Resolve Merge Conflicts Manually

            # Then push to LTS
            git push --set-upstream upstream ${{ env.MAX_LTS }}
            ```
      - name: Setup conda
        if: steps.cherryPickStep.outcome == 'success'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: isis
          environment-file: environment.yml
          auto-activate-base: false
          auto-update-conda: true
      - name: Check Environment (Debug)
        if: steps.cherryPickStep.outcome == 'success'
        env: 
          ISISROOT: ${{ github.workspace }}/build
        run: |
          echo "--- Conda Env"
          conda info --envs
          echo "--- cmake Location (Should be in isis conda env)"
          which cmake
          cmake --version
          echo "--- python location"
          which python
          echo "--- Working Directory"
          pwd
          echo "--- Files"
          ls
          echo "--- ISISROOT"
          echo $ISISROOT
      - name: Build ISIS
        if: steps.cherryPickStep.outcome == 'success'
        env: 
          ISISROOT: ${{ github.workspace }}/build
        run: |
          mkdir build
          cd build
          cmake -GNinja -DJP2KFLAG=OFF ../isis
          ninja -j8
      - name: Successful Cherry Pick - Auto Push to LTS
        if: steps.cherryPickStep.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
  
  # cherrypick-prod:
  #   needs: check_labels
  #   # Run this step if code was a bugfix or non-breaking change
  #   if: contains(needs.check_labels.outputs.result, 'production_update_')
  #   runs-on: ubuntu-22.04
  #   defaults:
  #     run:
  #       shell: bash -l {0} # bash login mode so conda can auto activate isis env
  #   permissions:
  #     pull-requests: write
  #     contents: write
  #   env: 
  #     MAX_PROD: ${{ needs.check_labels.outputs.maxprod }}
  #   steps:
  #     - name: Get PR number
  #       id: getpr
  #       uses: bcgov/action-get-pr@v0.1.0
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #         ref: '${{ env.MAX_PROD }}' # This branch must exist in the repo.  Target Prod changes branch.
  #         fetch-depth: '0'
  #     - name: Configure git
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #     - name: Cherry Pick
  #       id: cherryPickStep
  #       continue-on-error: true
  #       run: git cherry-pick -m 1 $GITHUB_SHA
  #     - name: Failed Cherry Pick - Comment
  #       if: steps.cherryPickStep.outcome == 'failure'
  #       uses: thollander/actions-comment-pull-request@v3
  #       with:
  #         github-token: '${{ secrets.GITHUB_TOKEN }}'
  #         pr-number: '${{ steps.getpr.outputs.pr }}'
  #         message: |
  #           Maintainers: Please cherry-pick this bugfix to Production.  
  #           PR:  #${{ steps.getpr.outputs.pr }}
  #           SHA: ${{ github.sha }}.  

  #           You may use the following commands to cherry-pick 
  #           (Assuming you have the DOI-USGS/ISIS3 repo as a remote named `upstream`):
  #           ```
  #           git fetch upstream
  #           git checkout -b cherry-${{ steps.getpr.outputs.pr }} upstream/${{ env.MAX_PROD }}
  #           git cherry-pick -m 1 ${{ github.sha }}

  #           # Resolve Merge Conflicts Manually

  #           # Then push to LTS
  #           git push --set-upstream upstream ${{ env.MAX_PROD }}
  #           ```
  #     - name: Setup conda
  #       if: steps.cherryPickStep.outcome == 'success'
  #       uses: conda-incubator/setup-miniconda@v3
  #       with:
  #         miniconda-version: "latest"
  #         activate-environment: isis
  #         environment-file: environment.yml
  #         auto-activate-base: false
  #         auto-update-conda: true
  #     - name: Check Environment (Debug)
  #       if: steps.cherryPickStep.outcome == 'success'
  #       env: 
  #         ISISROOT: ${{ github.workspace }}/build
  #       run: |
  #         echo "--- Conda Env"
  #         conda info --envs
  #         echo "--- cmake Location (Should be in isis conda env)"
  #         which cmake
  #         cmake --version
  #         echo "--- python location"
  #         which python
  #         echo "--- Working Directory"
  #         pwd
  #         echo "--- Files"
  #         ls
  #         echo "--- ISISROOT"
  #         echo $ISISROOT
  #     - name: Build ISIS
  #       if: steps.cherryPickStep.outcome == 'success'
  #       env: 
  #         ISISROOT: ${{ github.workspace }}/build
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake -GNinja -DJP2KFLAG=OFF ../isis
  #         ninja -j8
  #     - name: Successful Cherry Pick - Auto Push to LTS
  #       if: steps.cherryPickStep.outcome == 'success'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: git push