name: Github Actions - Build Anaconda Release

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }} 
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

on:
  release:
    types: [prereleased, released]
  push:
    branches:
      - '*.*.*_RC*'
      - '*.*.*_LTS'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-13, macos-14]  # Ubuntu, macOS x86_64, macOS arm64
          os: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          auto-update-conda: true
          use-mamba: true

      - name: Build Release
        env:
          ISIS_VERSION: ${{ github.event.release.tag_name || github.ref_name }}
        run: |
          mamba install conda-build anaconda-client
          git fetch origin
          if [[ "$ISIS_VERSION" =~ .*_RC[0-9]$ ]]; then 
            git checkout $ISIS_VERSION
          else 
            git checkout refs/tags/$ISIS_VERSION
          fi
          cd recipe
          echo $ENCRYPTION_KEY | openssl enc -aes-256-cbc -d -in kakadu/kakadu_7_9.zip.enc -out kakadu/kakadu_7_9.zip -pbkdf2 -iter 10000 -pass stdin
          unzip -j kakadu/kakadu_7_9.zip -d /tmp/kakadu_7_9 -x "__MACOSX/*"
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|/isisData/kakadu|/tmp/kakadu_7_9|g" build.sh
          else
            sed -i "s|/isisData/kakadu|/tmp/kakadu_7_9|g" build.sh
          fi

          if [[ "$ISIS_VERSION" =~ .*_RC[0-9]$ ]]; then 
            conda build . -c conda-forge -c usgs-astrogeology --override-channels --user usgs-astrogeology --label RC
          elif [[ "$ISIS_VERSION" =~ .*_LTS$ ]]; then 
            conda build . -c conda-forge -c usgs-astrogeology --override-channels --user usgs-astrogeology --label LTS
          else 
            conda build . -c conda-forge -c usgs-astrogeology --override-channels --user usgs-astrogeology --label LTS --label main
          fi

          BUILT_DIR=$(conda info --base)/conda-bld
          BUILT_PACKAGE=$(find "$BUILT_DIR" -name "isis-${ISIS_VERSION}-*.conda" | head -n1)
          echo "$BUILT_PACKAGE" > built_package.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package-${{ matrix.os }}
          path: built_package.txt
  
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
    env:
      ISIS_VERSION: ${{ github.event.release.tag_name || github.ref_name }}
      
    steps:
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          conda-remove-defaults: "true"
          auto-update-conda: true
          use-mamba: false

      - name: Conda install and test spiceinit
        run: |
          export ISISROOT=$CONDA_PREFIX
          if [[ "$ISIS_VERSION" =~ .*_RC[0-9]$ ]]; then
            conda install -c conda-forge -c usgs-astrogeology usgs-astrogeology/label/RC::isis=${ISIS_VERSION} -y
          elif [[ "$ISIS_VERSION" =~ .*_LTS$ ]]; then
            conda install -c conda-forge -c usgs-astrogeology usgs-astrogeology/label/LTS::isis=${ISIS_VERSION} -y
          else
            conda install -c conda-forge -c usgs-astrogeology isis=${ISIS_VERSION} -y
          fi
          conda list isis
          spiceinit -h
     
      - name: Cleanup Anaconda package if spiceinit fails
        if: failure()
        run: |
          echo "Cleaning up Anaconda download..."
          BUILT_PACKAGE=${{ needs.build.outputs.built_package }}
          echo "Removing package: $BUILT_PACKAGE"
          anaconda --token ${{ secrets.ANACONDA_TOKEN }} remove usgs-astrogeology/isis/${BUILT_PACKAGE} -y