name: versionbump
on:
  push:
    branches:
    - dev
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: |
          git config --global user.name 'ProjectBot'
          git config --global user.email 'bot@users.noreply.github.com'
          version=$(sed -n '0,/^{% set version = "\([^"]*\)" %}/s//\1/p' meta.yaml)
          VERSION=`echo $VERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.`
          sed -i "0,/^{%.*version.*\"\([^\"]*\)\".*/s//{% set version = "${version}" %}/" meta.yaml
          git add module.xml
          git commit -m 'auto bump version'
          git push
