name: versionbump
on:
  pull_request:
    branches:
      - lts
    types:
      - closed

jobs:
  version_bump:
    if: github.event.pull_request.merged && ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: |
          git config --global user.name 'ProjectBot'
          git config --global user.email 'bot@users.noreply.github.com'
          CURRENTVERSION=$(sed -n '0,/^{%[[:space:]]*set[[:space:]]*version[[:space:]]*=[[:space:]]*"\([^"]*\)"[[:space:]]*%}/s//\1/p' ${{github.workspace}}/recipe/meta.yaml)
          CURRENTVERSION=`echo $CURRENTVERSION | awk -F. '/[0-9]+\./{$NF;print}' OFS=.`
          NEWVERSION=`echo $CURRENTVERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.`
          sed -i "0,/^{%.*version.*\"\([^\"]*\)\".*/s//{% set version = "\"${NEWVERSION}"\" %}/" ${{github.workspace}}/recipe/meta.yaml
          sed -i "0,/set(VERSION.*/s//set(VERSION \""${NEWVERSION}"\")/" ${{github.workspace}}/isis/CMakeLists.txt          
          git add ${{github.workspace}}/isis/CMakeLists.txt ${{github.workspace}}/recipe/meta.yaml
          git commit -m 'auto bump version'
          git push
