APPNAME = shadowtau

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/TAU_INPUT_A.LIS to=$(OUTPUT)/hapkehen2.txt \
	phtname=hapkehen wh=0.52 hh=0.17 b0=0.025 theta=30 hg1=-0.213 hg2=0 \
	zerob0st=true atmname=hapkeatm2 wha=0.95 hga=0.68 hnorm=0.003 \
	> /dev/null;
