APPNAME = trim

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/isisTruth.cub \
	  to=$(OUTPUT)/trimTruth1.cub \
	  top=0 \
	  bottom=10 \
	  left=3 \
	  right=1 > /dev/null;
